config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml

It does not look like the PacketMachine needs a ProjectID. It is a value
that we get from the PacketCluster.
It is not even generated from the `make examples` file and when applied
via kubectl it fails because PachetMachine.ProjectID is a required field
in openapi.

remove the projectID from PacketMachine crd

---

.drone.yml
Makefile

At the end of the story it took me an hour to understand the issue and 1
minutes to fix it. I suppose.
The kubebuilder installation process is already part of the Makefile,
but it was not used in CI.
now it should work.

fix ci installing kubebuilder

---

Dockerfile

It is cool that we cache the go dependency as a separate layer so images
will take care of caching for us! But it does not come for free!!

fix ci image build test

---

controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
main.go

If we attempt to remove a machine that is not running on Packet (for any
reason), we are in a loop where the reconciler returns 404 from Packet
API and the source never gets deleted.
This code should check for a 404, and it should pass forward the
finalizer trigger a garbage collection.
I presume we do not need to check for the number of `instances` anymore,
because if they are `0` we never get over the `not found error`.

trigger finalizer even if the machine is already deleted from packet

---

controllers/packetmachine_controller.go

From v1alpha2 to v1alpha3 the Bootstrap.Data field got deprecated in
favour of Bootstrap.DataSecretName as you can see:
https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#data-generated-from-a-bootstrap-provider-is-now-stored-in-a-secret

bootstrap data secret must be set

---

Makefile
docs/BUILD.md

I got tired of doing this manually.

simplify manual install of a new cluster with make target

---

api/v1alpha3/types.go
controllers/packetmachine_controller.go

By default we mark a machine as failed when we receive an unrecognized
state. We were not handling the `provisioning` state.

handle device in provisioning state

---

templates/cluster-template.yaml

The right way to go here is via MachineSet, MachineDeployment.
Those are almost the equivalent of ReplicaSet and Deployment for pod.
* MachineSet represents an immutable group of Machine
* MachineDeployment manage the lifecycle of MachineSet
I updated our example to use those for pod rollout.
By consequence the example also uses KubeadmConfigTemplate and
PacketMachineTemplate
Control Plane management will come in another PR.

update example to use MachineDeployment

---

Makefile
README.md
config/manager/credentials.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
docs/BUILD.md
scripts/generate-cluster.sh
templates/cluster-template.yaml

This provides support for clusterctl in two ways.
First, it properly structures it so you can run `clusterctl --config=...` to initialize the Packet provider. It did work before, but there were elements missing. This completes it so that it works. As part of it, it needed to change some of how the templates are generated to `./out/`.
Second, it adds support for the cluster template in the right directories in `./out/`. This means that `generate-example.sh` is no longer relevant, although it uses the same source template. This now is pushed into the correct `./out/` directories, where `clusterctl` can consume them.
Since `clusterctl config cluster` does _not_ (yet) support defaults - every env var _must_ be set for it to work - this repurposes `generate-example.sh` to …

clusterctl support

---

Makefile
pkg/cloud/packet/client.go
templates/cluster-template.yaml

Does a few things:
* inject the apiKey into the userData where needed when actually deploying a control plane machine, so it no longer needs it in the template (as it shouldn't)
* removes the apiKey from the template
* fixes some missing info in the Makefile that was causing it not to regenerate

Remove PACKET_API_KEY fron cluster template

---

templates/cluster-template.yaml

I do not know why, but applying this without these fields causes it to fail. Since it is auto-generated, it doesn't hurt.

add missing fields

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yml
Dockerfile.goreleaser
Makefile
docs/contribution/release.md

GoReleaser is a cool and powerful tool to manage releases for Go code.
It highly configurable and flexible via YAML file.
The goal for this are:
GitHub release page.
required maniafest and binaries to the GitHub page
release will look like

Goreleaser to manage release

---

Makefile

Fixes Makefile in 2 ways:
* ensures that the URL referenced in `clusterctl.yaml` for the release points to the correct release file
* refuses to run if the version is not discoverable
The next fix (which you offered to do @gianarb :-) ) is to:
* use the most recent tag, not just the one on head
* if there is no recent tag, just use `v.0.0.0`

fix usage of version

---

.goreleaser.yml

It looks like gorelaser does not support templating `{{ .Tag }}` as
release blob file.

load manifest file as part of github release

---

.goreleaser.yml
Makefile

GoReleaser does not have a solid history where it comes to Docker image
multi arch. What I am doing here is to try to get something working with
buildx that I can generalize as well with the GoReleaser community.

move from goreleaser docker to buildx as custom publisher

---

.goreleaser.yml
scripts/multi_arch_docker_release.sh

This failed during our last build
```
auto-push is currently not implemented for docker driver
```
Gooling it looks like by default docker does not work for auto push, but
if you create a non-default one it works

buildx has some requirements like having a platform

---

.github/workflows/release.yaml
scripts/multi_arch_docker_release.sh

During the last release gh action I got this error:
```
server message: insufficient_scope: authorization failed
```
Looking around I found this:
https://github.com/docker/buildx/issues/202#issuecomment-597375245
Also, -1 action to use

buildx unauthorized

---

config/rbac/role.yaml
controllers/packetmachine_controller.go

The manager has to be able to retrieve secrets because that's how it
lookup bootstrap information. We didn't set the right permission
```
$ kubectl logs -f cluster-api-provider-packet-controller-manager-89c9f95b8-49hlq -n cluster-api-provider-packet-system -c manager -f
E0526 15:16:07.696352       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:cluster-api-provider-packet-system:default" cannot list resource "secrets" in API group "" at the cluster scope
E0526 15:16:08.698025       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:cluster-api-provider-packet-system:defaul …
```

fix: error retrieving bootstrap secret from kube api

---

scripts/generate-cluster.sh

In the `make cluster` script, have an option to override the path to `clusterctl`. This is useful for testing specific paths and versions

option to override clusterctl

---

config/resources/manager/credentials.yaml

add base64 PACKET_API_KEY

---

templates/cluster-template.yaml

I forgot this line during previous tests.
The CNI installation is a follow-up step that users have to take by
their own.
Or they can write their own cluster.yaml that contains what they like.
Fixed #11

remove calico from cluster template

---

OWNERS_ALIASES

I copy pasted the previous list from a repo that was not up to date.
https://github.com/kubernetes/org/issues/1934#issuecomment-649716767

chore: update list of cluster-lifecycle admin/maintainers

---

api/v1alpha3/packetmachine_types.go
config/resources/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
config/resources/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
config/resources/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
pkg/cloud/packet/client.go

This PR will add a new field to packetmachine that allows for the
passing of a pxe url string. If present, we check that the OS is also
set to "custom_ipxe" so that we can fail early.
Will close #131 
Related issue #118 
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

feat: support use of pxeurls in machine provisioning

---

templates/cluster-template.yaml

As you know kubelet requires swap to be off in order to run
successfully.
I was using the command `swapoff -a` but it does not work after a
reboot because the swap turns on again.
This PR fixes the issue by modifying the fstab file.
/assign @deitch 
/kind bug

Swapoff command does not get persisted

---

pkg/cloud/packet/client.go

Use a more verbose tag to mark the elastic IP

---

templates/cluster-template.yaml

This PR Updates the CCM to [1.0.1](https://raw.githubusercontent.com/packethost/packet-ccm/9779a5b1dcaa039c40159a6a2c2e57b8ab4874d8/deploy/releases/v1.0.1/deployment.yaml) and pins the URL to a commit (a tag is not available) so changes on the relative `master` will not break the URL.
Closes #151

update packet-ccm to 1.0.1 (with a pinned url)

---

controllers/packetmachine_controller.go
pkg/cloud/packet/client.go
templates/cluster-template.yaml

One of the Packet CCM responsability is to check the status of the
Control Plane Endpoint (an elastic ip) keeping it assigned to an healthy
control plane.
In order to do that it needs to know the key=pair used to tag the
elastic ip at creation phase. This PR pass this information to CCM via
Kubernetes Secret

Teach ccm what it needs to look after the control plane endpoint

---

README.md

`(./templates/cluster.yaml)` -> `(./templates/cluster-template.yaml)`

Fix broken link to cluster template

---

pkg/cloud/packet/client.go

When converting the IPs from the device to kubernetes machine I didn't
render the right content (just the IP) but the entire Go object.
Fixed #157 
/kind bug
/assign @deitch

The addresses do not contains the right value but a Go obj

---

PROJECT
README.md
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
controllers/suite_test.go
docs/concepts/machine.md
go.mod
go.sum
hack/tools/go.mod
main.go
pkg/cloud/packet/client.go
pkg/cloud/packet/scope/cluster.go
pkg/cloud/packet/scope/machine.go

In this PR:
* package name was updated to `sigs.k8s.io/cluster-api-provider-packet`
* `go mod tidy` was run
* README badges were added (some referring to the new package name which won't work until after this is merged)
* golanglint-ci linter warnings were corrected (unused `packageName`, ineffectual assignment)
* Link was added to <https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-packet/> when discussing the `PacketMachine` spec
There are still references to `packethost/cluster-api-provider-packet` in the context of the Docker repo.
There are still references to `kubernetes-sigs/cluster-api-provider-packet` in the context of Github issues, releases, and workflows.
Closes #164

Update module path to sigs.k8s.io/cluster-api-provider-packet

---

templates/cluster-template.yaml

This PR enables the Elastip IP management for Control Plane in CCM.
One of the Packet CCM responsibility is to health check the Control
Plane IP and move the Elastic IP to an healthy control plane.
In order to do that the configuration has to be set to CCM secret.

Enable Control Plane elastic ip management in CCM

---

config/resources/manager/manager.yaml
main.go

Similar was made here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1487 and https://github.com/kubernetes-sigs/cluster-api/pull/2156
Adding the liveness and readiness probes for cluster-api-provider-packet

✨ manager: add health probes

---

main.go

Add the option to check in which namespace should watch for the leader election.
Also changed the name of the `LeaderElectionID` setting.

✨ manager: add leader election namespace option

---

main.go

Add an option to the user to configure the sync time, the minimum interval at which watched resources are reconciled

manager: add option to configure the sync time

---

config/release/kustomization.yaml

Probably there is a new check that prevents clusterctl to work if an
the image does not follow the canonical naming convention.
This PR should fix this issue and it should make `clusterctl init` working
again.
fixed #184

🐛 clusterctl init fail because manager does not use a canonical image name

---

hack/tools/go.mod
hack/tools/go.sum

kustomize v3.8.2 has a bug that causes it to not update the name of the Namespace (https://github.com/kubernetes-sigs/kustomize/issues/2867).
The issue is fixed in v3.8.4
Fixes #187

:bug: Update kustomize to fix template generation

---

templates/cluster-template.yaml

This PR fetches all the version from the apt cache and filters based on the `KUBERNETES_VERSION` provided by the cluster configuration.
This PR doesn't pin / hold that installed version, meaning that it should still be able to upgrade as expected; I need to provide tests for this.

feat: allow installation of the latest semantic version

---

templates/cluster-template.yaml

Unfortunately, the quotes in this `awk` command are escaped by `cloud-init`, causing the regex matcher to fail; and no version of the kubelet, kubeadm, and kubectl are installed.

fix: remove superfluous quotes that break semantic version matcher

---

templates/cluster-template.yaml

The `envsubst` needs us to escape the variables that won't exist at template render time with `$$`

🐛 escape / defer interpolation of TRIMMED/RESOLVED variables to runtime

---

templates/cluster-template-crs.yaml
templates/cluster-template.yaml

- Adds a cluster template that uses ClusterResourceSet for CNI deployment
- Adds some defaults
To test this out, you will need to:
- Set `EXP_CLUSTER_RESOURCE_SET=true` when running `clusterctl init`
- Use `--from` to point to the template when running `clusterctl config`, if the cluster-template-crs.yaml file was attached to a release, then it would be possible to use `--flavor=crs` rather than `--from`
The template can be tested with the currently released images

*sparkles* Cluster Resource Set

---

Makefile
config/kustomization.yaml
config/manager/manager_image_patch.yaml
test/e2e/config/packet-dev.yaml

Fixes up issues with the e2e test configuration
Builds on top of https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/197

:running: e2e fixes

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
controllers/packetmachine_controller.go

Prevents the PacketMachine controller from treating an error indicating a lack of reservations as a fatal error, this allows the controller to continue to retry instance creation until a reservation is available.

:bug: Do not treat lack of reservations as a fatal error

---

controllers/packetmachine_controller.go

Fixes crash on Machine creation that was introduced in v0.3.6

:bug: Fix error handling on Machine creation

---

pkg/cloud/packet/client.go

Fixes a typo in an error message

:sparkles: Fix typo in error message

---

templates/cluster-template.yaml

Other commands which are executed are also privileged, so using sudo
shouldn't be needed.
This is nice to enhance the consistency.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

:sparkles: templates/cluster-template.yaml: consistently don't use sudo

---

pkg/cloud/packet/client.go
templates/cluster-template.yaml

The Kubernetes version on the Machine resource is currently being ignored, this change should set the version used by the cloud-init script at runtime instead of at template instantiation time.

:bug: Set kubernetes version for cloud-init during runtime

---

api/v1alpha3/packetmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
config/rbac/role.yaml
pkg/cloud/packet/client.go

Allows the ability to override the facility per PacketMachineTemplate. Use case would be to launch a MachineDeployment into another datacenter but still be connected to the primary cluster.
Fixes #228

✨  Allow overriding facility

---

config/rbac/auth_proxy_service.yaml

prometheus as the defacto standard for monitoring in a kubernetes
environment is generally configured to scrape metrics only if the
observed targets (pods, service, endpoints) has set proper annotations.
- [related PR with documentation on `cluster-api`](https://github.com/kubernetes-sigs/cluster-api/pull/4247)
- [official prometheus config example](https://github.com/prometheus/prometheus/blob/release-2.25/documentation/examples/prometheus-kubernetes.yml#L143-L183)
- corresponding implementation on other providers (all others didn't set the annotation yet - i'm on it)
- [AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/rbac/auth_proxy_service.yaml)
- [Metal3](https://github.com/metal3-io/cluster-api-provider-metal3 …

🐛 enable metrics scraping via prometheus

---

config/manager/manager.yaml

Increases the default memory requests/limits for the cluster-api-provider-packet deployment
Fixes #233

:sparkles: Increase defaults limits/requests for deployment

---

.github/dependabot.yml
.github/workflows/ci.yaml

- Adds a dependabot configuration to proactively update dependencies for Go, github workflows, and docker images
- Updates the go version used for CI to v1.15

:running: Add dependabot config and update go version for testing to v1.15

---

.github/workflows/pr-post.yml

This workflow will run e2e tests using artifacts previously built.
This is needed to test the PR workflow changes in #269 and enable e2e smoke tests to be run with each PR.

:running: Add a workflow for running the e2e tests

---

.github/workflows/pr-post.yml

Try to actually run the e2e tests from the previously uploaded artifacts.

:running: Update pr-post workflow to attempt to run e2e

---

.github/workflows/pr-post.yml

Fixes a permissions error when trying to run the e2e test binary from artifacts and removes unnecessary setup-go action.

:running: Fix issue with pr-post workflow

---

.github/workflows/pr-post.yml

- Remove unnecessary ls step
- Use absolute path for artifacts when calling e2e test.

:running: Fix bugs with pr-post workflow

---

.github/workflows/ci.yaml
docs/RELEASE.md

Updates the repo to reflect the new default branch of main instead of master

:running: Update to reflect renaming of master branch to main

---

OWNERS

subproject or SIG labels are not needed on subproject PRs/issues as they are implied.
helps for better org wide triage on SIG CL tickets, coming from third parties.
NONE
/kind cleanup
/priority backlog

remove SIG label from OWNERS file

---

OWNERS_ALIASES
SECURITY_CONTACTS

- Update cluster-api-admins group to reflect current state of the Cluster API Project
- Update cluster-api-maintainers group to reflect the current state of the Cluster API Project
- Update cluster-api-packet-maintainers:
- Remove gianrb, thebsdbox, and mrmrcoleman since they are no longer active in the project
- Add displague and cprivite for project continuity purposes (detiber leaving Equinix)
- Update security contacts to reflect current maintainership
Signed-off-by: Jason DeTiberus <detiber@users.noreply.github.com>
Pending membership for @cprivite here: https://github.com/kubernetes/org/issues/3355

Update Project Owners and Security Contacts

---

Makefile
api/v1alpha3/packetcluster_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1beta1/packetcluster_types.go
api/v1beta1/packetcluster_webhook.go
config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
config/default/config.yaml
config/default/kustomization.yaml
config/default/kustomizeconfig.yaml
config/default/manager_credentials_config_patch.yaml
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
pkg/cloud/packet/client.go
templates/addons/calico.yaml
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip/kustomization.yaml

Replacement of: https://github.com/detiber/cluster-api-provider-packet/pull/65.
What this PR does / why we need it:
This replaces the binding of an elastic IP to one of the control plane nodes with deploying kube-vip and having it load balance the Kubernetes API between the various control plane nodes.

✨ Add support for kube-vip

---

pkg/cloud/packet/client.go

Include IP assigmenets when reconciling VIP ips

---

templates/cluster-template-crs-cni.yaml
templates/cluster-template.yaml

Bumps CPEM verison to 3.4.3
Puts the systemctl restart networking line back into the templates.
Fixes #361

:bug: Fix CPEM issues

---

templates/cluster-template-crs-cni.yaml
templates/cluster-template.yaml

What this PR does / why we need it:
Bumps CPEM verison to 3.4.3
Puts the systemctl restart networking line back into the templates.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #361

:bug: Update Cloud Provider Equinix Metal Version

---

.github/workflows/ci.yaml

Switch the CI to use machines in the DA11 facility. DA6 does not have the machine type we want.
For #360

:sparkles: Use da11 as that's where machines are.

---

cmd/ci-clean/main.go
pkg/cloud/packet/client.go
test/e2e/common_test.go
test/e2e/suite_test.go
version/version.go

Add user-agent support to the equinix metal api calls so we can do analytics and tell how many people are using what version of CAPP.

:sparkles: Add User-Agent support for Equinix Metal Calls

---

test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

Add 1.1.99 section for tilt
This bumps the cluster-api module version used by tests to 1.1.3, which is what we currently support.
This also adds a 1.1.99 section (aka the "Next") version, for testing with things like tilt that want to use the current source files.
Fixes #375

:sparkles: bump cluster-api to 1.1.3

---

Makefile
pkg/cloud/packet/client.go
test/e2e/common_test.go
test/e2e/suite_test.go
version/version.go

Add default gitversion to version.go
Fix the useragent code added in the last PR.

🐛  Update packngo calls

---

Makefile
cmd/ci-clean/main.go
pkg/cloud/packet/client.go

The capp e2e testing useragent overrides via ldflags resulted in an akward situation. The few calls to equinix metal done by the e2e test code itself had the correct useragent, but the majority of calls via the manager did not, due to the CI framework pre-building the manager and thus not gettting any of the ldflag overrides from the E2E tests.
Current thinking is to add an Environment variable in the future which can add more UserAgent information. #385

:sparkles: Remove-capp-e2e-tags

---

Makefile
clusterctl-settings.json
cmd/ci-clean/main.go
pkg/cloud/packet/client.go

The upgrade tests use version 1.1.99 (.01 less than the next big upstream version) to represent an image with the latest source code files. This PR fixes the clusterctl-settings.json file to specifically tell clusterctl that this version exists. This file is managed in a python script in upstream cluster-api and we should probably do the same here.

:bug: Fix upgrade tests

---

README.md

Add documentation on how to use kube-vip by passing the --flavor tag
Update defaults section
**What this PR does / why we need it**: Update readme to reflect kube-vip flavor.
Fixes #381

📖 Add example documentation for using kube-vip version of CAPP

---

Makefile
templates/addons/calico.yaml
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip-crs-cni/kustomization.yaml
templates/experimental-kube-vip/kustomization.yaml
test/e2e/capi_e2e_clusterctl_upgrade_test.go
test/e2e/capi_e2e_conformance_test.go
test/e2e/capi_e2e_quickstart_test.go
test/e2e/capi_e2e_self_hosted_test.go
test/e2e/capi_e2e_test.go
test/e2e/capi_e2e_workload_upgrade_test.go
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml
test/e2e/data/v1beta1/cluster-template-kube-vip/kustomization.yaml

Bumps CPEM version
Bumps kube-vip version in kube-vip templates.
Bumps calico version in crs-cni templates.
Adds basic e2e test for kube-vip template.
fixes #373
fixes #382
fixes #397

✨ Update kube-vip version and add e2e tests

---

templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip/kustomization.yaml
test/e2e/config/packet-ci-actions.yaml

Update docker and k8s debian key registrations
Add crictl default container runtime configuration
Install kubetail on ubuntu 20+
export DEBIAN_FRONTEND=noninteractive once
Configure containerd to use Systemd cgroups
Configure containerd to use the pause image of installed k8s
Fixes #403

 ✨ Set up default environment for kubectl, crictl, etc.

---

README.md
docs/MIGRATION.md
docs/experiences/cni.md
docs/experiences/flavors.md

Updates the README with some install and debugging notes. Restructures the README.md

Readme updates

---

.github/dependabot.yml
Makefile

Fix dependabot config so it also updates e2e modules
Remove some commented out code in the makefile.
Fixes a dependabot request.

:bug: Fix dependabot PRs so gomod updates pass tests

---

README.md
clusterctl-settings.json
metadata.yaml
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

Update version in metadata.yaml for 0.6.0 release.

:running: Update-metadata-for-060-release

---

Makefile
scripts/go_install.sh

**What this PR does / why we need it:**
Updates scripts/go_install.sh file to use `go install` instead of `go get` which was deprecated in golang 1.17 and it no longer install packages after 1.18. It is required to execute e2e tests locally with latest go version, and will be required before update the go version in [all github actions and other references](https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/410). Issue https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/410 contains more information about the kustomize installation changes included in this PR.
**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):**
fixes …

Update go install script and add kustomize install script

---

Makefile
README.md
scripts/go_install.sh
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip/kustomization.yaml

Remove docker.io from apt-get remove line
Install containerd.io instead of containerd
Add quotes around the kubernetes pause image
Fixes #419

Fix errors in new templates

---

pkg/cloud/packet/client.go

This reverts commit 7429b477efa9ca7c30184dbc7a75e716b42405c5. (see #464)
Fixes #464

Revert "Include IP assigmenets when reconciling VIP ips"

---

README.md
docs/concepts/machine.md
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
test/e2e/data/v1alpha3/bases/md.yaml

**What this PR does / why we need it**: Use Ubuntu 22.04 as the default deployment OS and the testing OS. Equinix Metal will be disabling 18.04 in April.

:warning: Use Ubuntu 22.04 for testing and default deployments

---

test/e2e/go.mod

The cluster-api-provider-packet version number in the test/e2e/go.mod file should be v0.0.0-00010101000000-000000000000
Somehow I lost that along the way. I'm putting it back now.

Put dev version back into e2e go.mod

---

.golangci.yml
main.go

**What this PR does / why we need it**: This PR fixes the go fmt issues that were causing linting errors by adding a line between the top of file comments and the start of the code in main.go. It also backs out the .golangci.yml changes made in the last PR as they were a red herring and did not ignore commenting as thought.
Fixes #

:bug: Fix linting errors and revert golangci change

---

Makefile
test/e2e/common_test.go

Fixes a missing options parameter from the wrapper of the runtime client in the e2e tests. 
Also removes updates deprecated ginkgo flags we were using to avoid warning messages.

:bug: E2e-wrapped-client-fix

---

test/e2e/config/packet-ci.yaml
test/e2e/data/shared/v1beta1/metadata.yaml

**What this PR does / why we need it**: This adds 1.4 and 1.3 to the metadata.yaml file that tells clusterctl what version of the API each version of cluster-api uses. This file is used for the e2e tests. 
Fixes #

:bug: Update metadata.yaml to include definitions for 1.3 and 1.4 capi

---

test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

Add new intervals from upstream capi
Remove unused intervals
Extend machine-upgrade to 120m instead of 60m
Fixes #

Update e2e intervals

---

.github/workflows/ci.yaml
Makefile
scripts/go_install.sh
test/e2e/capi_e2e_clusterctl_upgrade_test.go
test/e2e/capi_e2e_self_hosted_test.go
test/e2e/capi_e2e_workload_upgrade_test.go

This is another attempt at resolving e2e test failures.
We make the ginkgo and directory config sections of the makefile more like upstream.
We define and override the default ginkgo test timeout of 1hr to be 6hr instead.
We rename ginkgo tests to use hyphens and have no spaces to be compatible with the new way focus and skip arguments are passed to ginkgo by upstream.

:bug: Update-e2e-harness

---

Makefile

**What this PR does / why we need it**: Due to the new quote style of the GINKGO_FOCUS and SKIP variables in the makefile, we need to not have single quotes in our GINGKO_FOCUS or GINKGO_SKIP definitions.
Fixes #

Remove single quote from test names

---

.github/actions/metadata/action.yaml
.github/actions/setup-go/action.yaml

Use newer images that aren't deprecated
Use newer env formatting instead of set-output
The current ones were going to be disabled soon.

:sparkles: Update github actions

---

.github/workflows/ci.yaml

**What this PR does / why we need it**: This PR adds the GITHUB_TOKEN to the 5 E2E test runs to avoid api rate limiting from github caused by requests from the clusterctl client.go code.

:sparkle: add github token to ci workflows

---

.github/workflows/ci.yaml
README.md
api/v1alpha3/packetcluster_types.go
api/v1alpha3/packetmachine_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1beta1/packetcluster_types.go
api/v1beta1/packetcluster_webhook.go
api/v1beta1/packetmachine_types.go
api/v1beta1/packetmachine_webhook.go
config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
pkg/cloud/packet/client.go
scripts/ci-e2e-capi-conformance.sh
scripts/ci-e2e-capi-management-upgrade.sh
scripts/ci-e2e-capi-quickstart.sh
scripts/ci-e2e-capi-workload-upgrade.sh
scripts/ci-e2e-capi.sh
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml

Signed-off-by: Moath Qasim <moad.qassem@gmail.com>
Signed-off-by: Chris Privitere <cprivitere@equinix.com>
Adding metro support to packet cluster api crds
Fixes #313
Continuation of https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/448

🏃 :sparkles: Add-metro-support

---

templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/experimental-kube-vip/kustomization.yaml

The kube-vip templates included an unnecessary reference to the `FACILITY` environment variable.  Removing that reference fixes the quickstart tests (when run locally, at least).
This removes the unnecessary references to the `FACILITY` environment variable from kube-vip-related templates.  These references were causing the quickstart tests to fail.
Fixes #573

:bug: Remove facility from kube-vip templates

---

README.md
docs/concepts/machine.md
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-packet-ccm.yaml
test/e2e/data/v1alpha3/bases/md.yaml

- Set our default OS to Ubuntu 20.04 due to bugs in the Ubuntu 22.04 image with DNS.

:bug: Move to 20.04 as default

---

scripts/fetch_ext_bins.sh

- Use the same kubebuilder tools upstream uses for our unit tests
- We were still using 1.16 tools

:sparkles: Sync up kubeuilder tools version to upstream

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

- Go back to quay as default as ghcr isn't publicly accessible on this repo
- re-add quay and docker to the metadata generation, this was an oversight on the earlier CI refactor
- Refactor the release ci yaml like we did to the main ci yaml
- remove caching
- Add tags to like we have in main ci
- Publish for arm/v7
- remove custom metadata action

:sparkles: Refactor release ci and go back to using quay as default 

---

.github/workflows/ci.yaml

- Registry was still invalid as $QUAY_REGISTRY
- Now explicitly defining it again

ci: update registry again to a valid format

---

.github/workflows/ci.yaml
.github/workflows/pr.yaml
.github/workflows/release.yaml

Adds GITHUB_TOKEN secret to the ci, release, and pr workflow files to help avoid rate limiting from many of tools we use that interact with the github api.
Additionally, I have removed creating the latest tag on the normal CI runs, only the release runs will make a latest entry going forward.

✨ Use GITHUB_TOKEN to avoid rate limits

---

api/v1alpha3/packetcluster_types.go
api/v1alpha3/packetmachine_types.go
api/v1alpha3/packetmachinetemplate_types.go
api/v1beta1/packetcluster_types.go
api/v1beta1/packetmachine_types.go
api/v1beta1/packetmachinetemplate_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_packetclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml

This PR adds shortNames to several packet CRDs.
**Which issue(s) this PR fixes**:
Fixes #421. 
Local Run:
```
NAME                              SHORTNAMES   APIVERSION                                NAMESPACED   KIND
packetclusters                    pcl          infrastructure.cluster.x-k8s.io/v1beta1   true         PacketCluster
packetmachines                    pma          infrastructure.cluster.x-k8s.io/v1beta1   true         PacketMachine
packetmachinetemplates            pmt          infrastructure.cluster.x-k8s.io/v1beta1   true         PacketMachineTemplate
```

✨Modify type.go to include shortNames for few Packet CRDs

---

.github/workflows/release.yaml

**What this PR does / why we need it**: The 0.7.0 release used ghcr.io as the default registry to publish to. However that registry is currently not public. This patch to the release workflow uses quay.io as the default registry. A (separate PR)[https://github.com/kubernetes/org/issues/4189] has been made to kubernetes-sigs to make the ghcr.io registry public.

:bug: use quay.io for default registry

---

.github/workflows/release.yaml

**What this PR does / why we need it**: This fixes the REGISTRY env variable in the release.yaml. The last change was invalid as you can't reference previous env variables inside of the env: section.

Fix REGISTRY CI variable in release.yaml

---

README.md
templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip/kustomization.yaml
test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml

Updates default cpem version to 3.6.2 to get an important fix CPEM. This fix enables it to allocate elastic IPs inside of metros when creating a loadbalancer.

:bug: Fix default CPEM to be able to use loadbalancers in metros

---

cmd/ci-clean/main.go
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
go.mod
go.sum
pkg/cloud/packet/client.go
test/e2e/common_test.go
test/e2e/go.mod
test/e2e/go.sum
test/e2e/suite_test.go
version/version.go

This PR replaces `packngo` with `metal-go` for all interactions with the Equinix Metal API.  The `metal-go` SDK is generated from the Equinix Metal API spec, and we will gradually replace all usage of `packngo` with `metal-go` to streamline support.
Fixes #

:running: Adopt metal-go

---

controllers/packetmachine_controller.go

**What this PR does / why we need it**: patchErr is never checked
**Which issue(s) this PR fixes** 
fixes #622

:bug: Fix patchErr not being checked in packetmachine_controller

---

templates/cluster-template-crs-cni.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/cluster-template.yaml
templates/experimental-kube-vip/kustomization.yaml

- Fix templates to use new k8s apt repository
- also fix incorrect posix test [ syntax

:bug: Fix templates to use new k8s apt repository

---

api/v1alpha3/packetmachine_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1beta1/packetmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachinetemplates.yaml
go.mod
go.sum
pkg/cloud/packet/client.go
test/e2e/go.mod
test/e2e/go.sum

Bumps our metal-go dep to v0.25.0.
Updates a few lines of code to be compatible with type changes.

:seedling: bump metal-go to v0.25.0

---

Dockerfile
hack/boilerplate/boilerplate.Dockerfile.txt

- Bumps dockerfile to use 1.20.10 as base builder image
- Also use current dockerfile builder syntax

:seedling: bump dockerfile to use Go 1.20

---

api/v1beta1/packetmachine_types.go
cmd/ci-clean/main.go
controllers/packetmachine_controller.go
go.mod
go.sum
pkg/cloud/packet/client.go
test/e2e/common_test.go
test/e2e/go.mod
test/e2e/go.sum
test/e2e/suite_test.go
version/version.go

The `metal-go` generated SDK has been essentially folded into the new `equinix-sdk-go` as a sub-package.  Future maintenance effort will be focused on `equinix-sdk-go`, which is at this point a drop-in replacement for `metal-go`, so switching to that will put us in the best position to get feature updates and bug fixes in the future.
N/A

chore: switch from metal-go to equinix-sdk-go

---

metadata.yaml
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

This PR adds the v0.8.0 version of CAPP to the metadata.yaml file and configures the E2E test config files to use the v0.8.0 version of CAPP.
Directions came from: https://github.com/kubernetes-sigs/cluster-api-provider-packet/blob/main/docs/RELEASE.md

:seedling: bump tags for 0.8.0 release

---

.github/dependabot.yml

**What this PR does / why we need it**: This PR updates CAPP's dependabot config to the new config used by upstream Cluster API. This is to get their latest optimizations to reduce the amount and frequency of dependabot PRs while still receiving important updates.

:seedling: feat: Update to upstream's new dependabot file to reduce frequency and amount of dependabot PRs

---

api/v1beta1/packetcluster_types.go
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
internal/emlb/emlb.go

:sparkles: Add EMLB deletion

---

test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

e2e tests are currently broken due to still referencing 1.6.0 in the packet-ci.yaml file. This will bump them to 1.7.3 so they can function correctly.

Fix e2e tests by bumping provider versions to 1.7

---

Makefile
api/v1beta1/packetcluster_types.go
controllers/packetcluster_controller.go
controllers/packetmachine_controller.go
docs/experiences/flavors.md
internal/emlb/emlb.go
templates/cluster-template-emlb-crs-cni.yaml
templates/experimental-emlb-crs-cni/kustomization.yaml
templates/experimental-emlb/kustomization.yaml
test/e2e/capi_e2e_quickstart_test.go
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml
test/e2e/data/v1beta1/cluster-template-emlb/kustomization.yaml

This template further progresses #693 by adding cluster deployment and e2e testing templates.
The initial EMLB PR provided a provisioning template, but this one is now properly generated via kustomize and created as part of `make generate-templates`.
Fixes #

:sparkles: Add EMLB based templates for testing and deployment

---

cmd/ci-clean/main.go
controllers/packetcluster_controller.go
internal/emlb/emlb.go

* public functions to list all load balanceras and pools in a project
* make functions to delete load balancers and load balancer origin pools public
* add functions to ci-clean to find and delete load balancers
Fixes #693

:sparkles: CI Cleanup of Equinix Metal Load Balancers

---

Makefile
templates/addons/calico.yaml

- Align version of kustomize to upstream cluster-api
- Use upstream method to build kustomize with go install
- Add yq to hack tools
- Use yq to fix calico yaml formatting (this is the best upstream recommendation to fix kustomize yaml mangling)
Fixes # 709

:sparkles: Use same kustomize version as upstream cluster-api

---

Makefile

make generate-templates doesn't ensure that yq has been compiled before trying to use it. Add $(YQ) to the dependencies line so it does so.
Fixes #779

:bug: Add $(YQ) as a make dependency to generate-templates

---

.golangci.yml
Dockerfile
clusterctl-settings.json
docs/RELEASE.md
hack/ensure-go.sh
metadata.yaml
pkg/cloud/packet/client.go
templates/cluster-template-emlb-crs-cni.yaml
templates/cluster-template-emlb.yaml
templates/cluster-template-kube-vip-crs-cni.yaml
templates/cluster-template-kube-vip.yaml
templates/experimental-emlb/kustomization.yaml
templates/experimental-kube-vip/kustomization.yaml
test/e2e/common_test.go
test/e2e/config/packet-ci-actions.yaml
test/e2e/config/packet-ci.yaml

**What this PR does / why we need it**: 
Release prep for v0.9.0
- Bump versions to v0.9.0
- Update release docs to mention more things that need to be bumped during a version
- Move golang in Makefile back to 1.21 to fix CI building
- Fix areas of e2e tests to better support EMLB testing and cleanup as well as remove some deprecations
Fixes #

Release-0.9.0

---

OWNERS_ALIASES

Signed-off-by: cprivitere <23177737+cprivitere@users.noreply.github.com>
**What this PR does / why we need it**: 
- The OWNERS_ALIASES file had incorrect members in the various upstream Cluster API and SIG Cluster Lifecycle groups, so I've updated those to the current memberships. 
- Second, I'm removing myself from the OWNERS file since I no longer work at Equinix and no longer maintain this project.

Update OWNERS_ALIASES and remove cprivitere
