kubernetes-sigs/cluster-api-provider-packet

main.go
The types.Machine or Cluster from v1alpha3 where not right registered to
the manager
=> fix manager adding custerv1 schema types

api/v1alpha3/packetmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_packetmachines.yaml, config/crd/kustomization.yaml
This is **not** yet complete. It resolves the contract issue, but not the providerID issue. Let's not merge this in until that part is complete as well.
=> fix annotations so the CRDs are correct

controllers/packetmachine_controller.go
=> set correct provider ID

controllers/packetcluster_controller.go, controllers/packetmachine_controller.go
Does two things:
* for cluster reconcile, be sure to set the status to ready so it can be used
* for machine delete, be sure to remove the finalizer once it is deleted
=> proper cluster reconcile loop, remove finalizers on delete

.github/workflows/ci.yaml
We try to push the image without building. Oops.
=> build image before trying to tag and push it out

.github/workflows/release.yaml
It looks like something changes in between and an old examples I had
does not work anymore.
=> fix docker login

.github/workflows/ci.yaml, Makefile
This also will push out images with tags if a git tag exists
=> add support for building and pushing images per arch and multiarch

.github/workflows/release.yaml
This PR contains a new workflows that gets triggered when a new release
happens. It generates and pushes release artifacts.
=> create release and upload manifest files

Makefile
=> proper download URL

README.md, scripts/generate-cluster.sh
Admittedly, the parsing logic is ugly, but hopefully the larger issue gets fixed and this goes away
=> Config logic doc

config/default/kustomization.yaml
These need to be on everything, per https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#labels
=> add required label

README.md
=> be clearer about number of works

README.md, scripts/generate-cluster.sh
also option to override config path for local for `make cluster`
=> update README to use clusterctl with built-in packet provider

controllers/packetcluster_controller.go, controllers/packetmachine_controller.go
https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html?highlight=paused#support-the-clusterx-k8siopaused-annotation-and-clusterspecpaused-field
=> Support for paused annotation

OWNERS
Fixed #114
This is a required step to get this done: https://github.com/kubernetes/org/issues/1934
=> Added owner file

CONTRIBUTING.md, LICENSE
=> Adopt Apache 2

main.go, scripts/controller-gen.sh, scripts/generate-cluster.sh, scripts/multi_arch_docker_release.sh, test/e2e/e2e.go, test/e2e/e2e_test.go, test/e2e/suite_test.go
Missing a couple of new lines in the copyright header
=> newline in copyright

templates/cluster-template.yaml
=> The projectID is fixed as part of the cluster template

templates/cluster-template.yaml
=> respect SERVICE_CIDR

main.go
manager: configure webhook port
Add the option to customize the webhook port.
=> ✨ manager: configure webhook port

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Adding Issues and PR templates
=> 📖  github: add Issue/PR templates

main.go
Add option to configure is the user wants to watch a specific namespace or all namespaces.
=> ✨ manager: add option to watch a specific namespace for reconciliation

controllers/packetcluster_controller.go
Corrects misspelling in error/log message.
=> 🏃 misspelling

templates/cluster-template.yaml
=> 🐛 control plane template should use correct variable

test/e2e/config/packet-ci.yaml
Fixes some issues with the e2e config that were causing it to fail.
=> :running: e2e config fixes

templates/cluster-template.yaml
This switches to using containerd as the CRI
Fixes #215
=> ✨ use containerd as CRI

.github/workflows/pr-post.yml
Take into account that the download artifact action does not work correctly in the workflow_run context
=> :running: Update pr-post github action

.github/workflows/pr-post.yml
=> :running: Fix typo

.github/actions/metadata/action.yaml, .github/workflows/ci.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml
Publish images to multiple registries
- Also use quay.io by default
=> 🏃🏻‍♂️ Publish images to multiple registries

.gitignore, cmd/ci-clean/main.go
=> Test cleanup does not appear to purge SSH keys

.github/workflows/ci.yaml
=> Update CI to fetch tags.

.github/workflows/pr.yaml, .github/workflows/release.yaml
=> Update pr and release to fetch tags.

Makefile
=> Add git diff HEAD to verify-gen

templates/cluster-template-crs-cni.yaml, templates/cluster-template.yaml
Reverts kubernetes-sigs/cluster-api-provider-packet#363
=> Revert ":bug: Fix CPEM issues"

metadata.yaml
We need the 1.1 series here for our 1.1.99 version next
=> :bug: Add release series to metadata.yaml file

templates/addons/calico.yaml
Update the calico manifest in the repo which fixes the make generates of the e2e tests.
=> :bug: Update Calico Manifest

docs/BUILD.md
=> :book: Update build guide

.github/workflows/ci.yaml
=> Update to only run scheduled test once a day.

.golangci.yml, api/v1alpha3/packetmachine_types.go, cmd/ci-clean/main.go, main.go
Update golanglintci config
Fix nolintlint lint suggestions
Fix gosec suggestion
Fixes #
=> 🐛 Linting Updates

.github/workflows/ci.yaml, .github/workflows/release.yaml
- Fix registry variable (remove it from release.yaml, update it in ci.yaml so it's valid action yaml)
=> :bug: Fix the registry variable in the release and ci yamls

README.md, docs/RELEASE.md, metadata.yaml, templates/cluster-template-crs-cni.yaml, templates/cluster-template-kube-vip-crs-cni.yaml, templates/cluster-template-kube-vip.yaml, templates/cluster-template.yaml, templates/experimental-kube-vip/kustomization.yaml, test/e2e/config/packet-ci-actions.yaml, test/e2e/config/packet-ci.yaml, test/e2e/data/v1alpha3/bases/cluster-with-kcp-cpem.yaml
- Update release docs to include the ci test yamls
- Bump default cpem to 3.6.1 to resolve issues with metal lb 0.12 and lower
- Bump metadata for the 0.7.0 release
Fixes: #567
=> Push Release v0.7.0

main.go
Updated component-base/logs instead of old logging style.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/546
=> Updated component-base/logs instead of old logging style

.github/dependabot.yml
=> ci: sync dependabot settings with upstream capi

Makefile, templates/cluster-template-development.yaml, templates/cluster-template.yaml, templates/development/kustomization.yaml
Create a new cluster-template-development.yaml file to help folks following the docker clusterctl quickstart directions avoid an error. File is just a copy of cluster-template.yaml. But it is fully generated and has its own kustomize directory so we can add customizations to it in the future if we decide we want to.
Fixes # 767
=> cluster-template-development

docs/experiences/flavors.md
Update flavor documentation to better explain EMLB and other VIP Manager options.
=> :book: Update flavor documentation to better explain EMLB and other VIP Manager options.
